# Generated by Django 4.2.6 on 2023-12-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classNo', models.IntegerField(db_column='classNo', primary_key=True, serialize=False)),
                ('className', models.CharField(db_column='className', max_length=100)),
            ],
            options={
                'db_table': 'class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lessonNo', models.IntegerField(db_column='lessonNo', primary_key=True, serialize=False)),
                ('lessonName', models.CharField(db_column='lessonName', max_length=100)),
            ],
            options={
                'db_table': 'Lesson',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tno', models.IntegerField(db_column='TNo', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='TName', max_length=100)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], db_column='Gender', max_length=100)),
                ('mobile', models.CharField(db_column='Mobile', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('researchField', models.CharField(db_column='researchField', max_length=200)),
            ],
            options={
                'db_table': 'Teacher',
                'managed': True,
            },
        ),
    ]
