# Generated by Django 4.2.6 on 2023-12-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_class_lesson_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminName', models.CharField(db_column='userName', max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=100)),
            ],
            options={
                'db_table': 'Admin',
                'managed': True,
            },
        ),
    ]
