# Generated by Django 4.2.6 on 2023-12-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='adminName',
            new_name='userName',
        ),
    ]
