# Generated by Django 4.2.6 on 2023-12-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_adminname_admin_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class',
            table='Class',
        ),
    ]
