# Generated by Django 4.2.6 on 2023-12-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
