# Generated by Django 4.2.6 on 2023-12-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(db_column='Sdept', default='null', max_length=100),
        ),
    ]
