# Generated by Django 4.2.6 on 2023-12-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
